version: "3.8"
services:
  vim:
    image: pcb_recognizer_dev
    build:
      context: ../apps/pcb_recognizer_dev
      dockerfile: Dockerfile
    container_name: pcb_recognizer_dev
    user: root
    working_dir: /usr/src
    environment:
      - DOCKER_USER=$USER
    volumes:
      - ../apps:/usr/src/apps
      - .:/usr/src/compose_files
    command: >
        sh -c "jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
    restart: unless-stopped
    ports:
      - 8888:8888
    networks:
      pcb_recognizer_network_dev:
        ipv4_address: 11.2.0.3

networks:
  pcb_recognizer_network_dev:
    external: true